spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/bookstoresystem
    username: root
    password: iamgroot
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update